/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef blacklist_CONSTANTS_H
#define blacklist_CONSTANTS_H

#include "blacklist_types.h"

namespace blacklist {

class blacklistConstants {
 public:
  blacklistConstants();

};

extern const blacklistConstants g_blacklist_constants;

} // namespace

#endif
